baseURL = "https://magefile.org"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Mage Documentation"
theme = "learn"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/magefile/mage/edit/master/site/content/"
  description = "Mage"
  author = "Nate Finch"
  showVisitedLinks = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Mage"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-github'></i> Github repo"
# identifier = "ds"
url = "https://github.com/magefile/mage"
weight = 10

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-twitter'></i> Twitter Account"
# identifier = "ds"
url = "https://twitter.com/MagefileDotOrg"
weight = 20